### ISSUE TITLE
Feature: double leaves per sheet

### ISSUE THREAD

**Issue by momijizukamori** [momijizukamori/bookbinder-js#1]
Add the ability to print double the number of leaves per sheet with the intention of cutting them in half after (ie, four pages on each side instead of two). Handy for people looking to make tiny books, and for dealing with paper (ie, if you have a large office printer that takes both letter and tabloid paper, the tabloid size is more likely to be the correct grain direction after cutting)

**Comment by Lottie16** [comment]
I’m 90% this is the quarto setting and can therefore be closed, giving this the fixed indirectly label so issue created can confirm and close issue or remove label as relevant

**Comment by momijizukamori** [comment]
yep, closing this!
