### ISSUE TITLE
Bug: Info icon does not render properly

### ISSUE THREAD

**Issue by jackal-ate-jill** [momijizukamori/bookbinder-js#10]
This issue may be Mac-specific - I did not encounter it on my Windows machine and have not tested it in other environments.

On my Mac (macOS Monterey 12.2), the small 'info' icon renders as a blank square in Chrome, Safari, and Edge. Firefox shows a square with some characters inside. See screenshots for examples. 
<img width="595" alt="Screen Shot 2022-03-07 at 11 50 32 AM" src="https://user-images.githubusercontent.com/89539963/157108366-bde195f4-39a0-463a-94ee-3cceea8143c1.png">
<img width="595" alt="Screen Shot 2022-03-07 at 11 56 37 AM" src="https://user-images.githubusercontent.com/89539963/157108378-4c897a91-0c0f-4e70-98fc-8fb413274de5.png">

The tooltip information works as-expected, it's just the icon that doesn't display. An icon may need to be bundled in with the app to ensure that it can be displayed properly in different environments.

**Comment by momijizukamori** [comment]
Hmm, it's using a unicode character there, but it may be OSX doesn't have good fallback fonts for extended unicode handling.

**Comment by sithel** [comment]
I just replaced with the ℹ️ emoji for now
