### ISSUE TITLE
Feature: Advanced control over scale and margin options

### ISSUE THREAD

**Issue by momijizukamori** [momijizukamori/bookbinder-js#12]
Give people options for how to place pages from the doc onto sheets, particularly when the doc page size does not match the sheet page size - for example, to split the difference in margins evenly between sides, or to put it all to one side or the other. Ideally with a nice little visual diagram to show what's happening!

**Comment by sithel** [comment]
Yoooooooo!
I'm actively working on this right now. Hope to have a PR up.... tomorrow?
Please let me know if I'm missing anything, but so far I've broken it down into:
 - scale: 'keep proportional' / 'stretch' /  'original'
 - positioning: 'centered' / 'snug against binding'
And I'm adding the option to manually pad top/bottom/fore edge/binding sides with specified white space (in points to start with) 
If you've got other suggestions (relative to this stuff) while I'm in the code, am happy to try and tackle 'em... let me know? 

(ugly UI so far, will fix before posting) 
<img width="399" alt="Screen Shot 2022-06-20 at 3 02 04 PM" src="https://user-images.githubusercontent.com/1319240/174682891-4fd57d5d-a58d-4c6a-a338-7c14743e11c7.png">

**Comment by sithel** [comment]
Basic functionality is there-- UI is hacky though and some folks wanted pts defined in CM as well-- leaving ticket open because cleanup of that UX could be done (let user specify unit?)

**Comment by Lottie16** [comment]
@sithel is this issue finished? The pr is merged

**Comment by sithel** [comment]
I guess now it is 🤷‍♀️
