### ISSUE TITLE
Imposer cannot do landscaped octavo pages layout. Requires different imposition

### ISSUE THREAD

**Issue by sithel** [momijizukamori/bookbinder-js#28]
Another from **marvinhere** — Tuesday, September 20 at 10:00 PM

>  i don't think the imposer can do landscape octavo pages, and the arrangement needed for that is different from portrait octavo pages. I figured this via manually printing a test using multiple pages

Photos were provided to expand upon this
![marvin3](https://user-images.githubusercontent.com/1319240/191419269-cdf505c1-abd8-41c0-ba6d-36936e26d12c.jpeg)
![marvin2](https://user-images.githubusercontent.com/1319240/191419275-a8dedd78-f4dc-45cf-8278-265fa623c6d2.jpeg)
![marvin1](https://user-images.githubusercontent.com/1319240/191419277-e645d693-8757-44de-baec-0bcc64b98b06.jpeg)

And further

>I also tried doing an octavo as the uhhhh the Dutch small books? think the John green specials
arranged the images as landscape on landscape octavo pages
when took it into a PDF editor to rotate them so theyre portrait
with the hope that the imposer will treat them as portrait pages that bc the book page contents are arranged landscape, will be read as the Dutch minis
![marvin4](https://user-images.githubusercontent.com/1319240/191419458-611569fa-c3a8-433f-b965-e50db02293a9.png)
>when what i wanted was
![marvin5](https://user-images.githubusercontent.com/1319240/191419573-beafe4d4-07b3-4e58-8614-cb413ff961a1.png)

Don't forget to ping marvin when completed

**Comment by Lottie16** [comment]
Closed by PR #37 I believe
