### ISSUE TITLE
Perfect Bound Signature Format appears to not work? 

### ISSUE THREAD

**Issue by sithel** [momijizukamori/bookbinder-js#29]
From discussions in #shop-talk on Oct 7th 2022 by Shang Timhua (Tim)[sprx77#2936] : https://discord.com/channels/726108551428440206/726108789161590916/1028166854205767752 

Looks like the perfect bound has a `Total Pages: NaN` and errors right away when you try to generate because `pagelist` is null at time of `writepages`

**Comment by momijizukamori** [comment]
I think a lot of the perfectbound logic is still straight-up ports from the
old bookbinder app (where iirc it ALSO doesn't work), so this... does not
surprise me lol

**Comment by sithel** [comment]
I've been told it's good. Good enough for me!
