### ISSUE TITLE
Missing layout

### ISSUE THREAD

**Issue by Re-n-Im** [momijizukamori/bookbinder-js#30]
Hi there!

That's a great app. Thank you for developing it. :)
I faced an issue while trying to setup printable PDF through that app. My case is as follows:
- I want to use A4 size paper with grain directed over the long edge;
- My input PDF is with pages wich width is half the A4 width;
![изображение](https://user-images.githubusercontent.com/15013975/195530197-b84bbbf5-e0e3-4c4d-98c4-e0e5b9dbafe1.png)

And the goal is to make PDF with such layout:
![изображение](https://user-images.githubusercontent.com/15013975/195530343-84104a77-9a7f-4f29-a28d-439884ef0f46.png)

But I couldn't achieve that setup in your app.
Do I miss something or if not, do you plan to add that kind of layout?

Thanks!

**Comment by sithel** [comment]
I wonder if you rotated the PDF pre-imposition if that'd work 🤔  (can't recall if it auto-rotates stuff...) (no- I see now, Folio definitely is set to hamburger fold the page) 

Is the alignment with the "top" of the page important here? Would centering it (but having the orientation like that) be ok? 

@momijizukamori -- is this what the "Alternate Page Rotation" setting is supposed to do?

**Comment by Re-n-Im** [comment]
Hi @sithel! Thank you for your reply!

To rotate PDF pages — this requires me to use software, other than I am using to generate PDF. I prefer not to use that approach.

No, the alignment of page on top is not mandatory. What I illustrated with a picture is just an example. And yes, centering is OK.

Thank you for your effort. :)

**Comment by Lottie16** [comment]
I believe this is solved now by #37

**Comment by Re-n-Im** [comment]
@sithel Hi, I didn't check this issue status since the end of 2022, that's why I am late with my answer.

Tested it and for now everything seems OK.

Thank you for that update!
