### ISSUE TITLE
[Discussion] Discord server for development/help?

### ISSUE THREAD

**Issue by momijizukamori** [momijizukamori/bookbinder-js#38]
Mostly because the main Renegade server has gotten WAY too big for me to keep up with any more, which is why I have not been around to do dev work much. It would also give an avenue for people not on the Renegade server who aren't familiar with Github to go to for help - I had some DM me on twitter because they were having issues (and I have not had a chance to investigate them because Life)

**Comment by sithel** [comment]
Oophf... I agree Renegade server is pretty big. The #coding channel is still rather calm, but I can still sympathize. 

I don't believe I personally would join a secondary server but can see the rational of making one/if it'd be helpful for you, go for it...

**Comment by Lottie16** [comment]
I’m all for it, there’s a lot of features a discord server has that the dev group chat we currently have doesn’t - we could make an announcements channel that other servers can subscribe to, so when a new feature goes on or a bug gets fixed, the announcement message also goes to the assigned channel in the subscribed server

**Comment by g33z** [comment]
Creating a merge request just now - would love to join some time.

**Comment by AlexNorb** [comment]
Was hoping to use this to create a simplified version with less option and different UI. Perhaps that could be of interest for this project also, ive seen some issues mentioning this. Would like to join you on discord for easier discussion/questions if thats possible?

**Comment by sithel** [comment]
Hi @AlexNorb! 
Definitely been a subject of discussion on the Discord, happy to have you join us: https://discord.gg/wQBnWT5m
