### ISSUE TITLE
BUG (?): Summary Transposing Number of Signatures & Signature Arrangement

### ISSUE THREAD

**Issue by tig-papermagic** [momijizukamori/bookbinder-js#41]
When I was working yesterday I noticed that the summary section here seems a bit buggy https://d.pr/i/O6TqUT. Sometimes the "Number of Signatures" number and "Signature Arrangement" numbers were transposed; in that screenshot it implies 4 total signatures of 6 pages each but what it actually produced was 6 total signatures of 4 pages each (which is what I wanted). So it's technically working, it's just that the summary is sometimes misleading (it jumped around a lot and kept spitting out different configurations of sheets per signature depending on what I changed in the "sheets per signature" box, although the total number of sheets in the aggregate didn't change).

**Comment by Lottie16** [comment]
From medrengirl on the discord

I'm having an odd problem on the Imposer this morning! the signature info section at the bottom is not producing the right information for the settings I have chosen. The actual PDF that is produced seems right, but the info section seems to be lagging one choice behind whatever I've chosen for the number of sheets per signature. (So if it had default set to 5 sheets per sig and I change it to 3, it shows me info for 5. If I then change it to 4, it shows me info for 3.)
