### ISSUE TITLE
Bookbinder: Website styling

### ISSUE THREAD

**Issue by yaten2302** [momijizukamori/bookbinder-js#52]
#### Description
Hi @momijizukamori, I was having an idea of designing a beautiful layout for the website - https://momijizukamori.github.io/bookbinder-js/

#### Screenshots

Before: 

![image](https://github.com/momijizukamori/bookbinder-js/assets/129659514/d1990af4-bf2a-4d2e-997d-76e2a74de59f)

After:

![image](https://github.com/momijizukamori/bookbinder-js/assets/129659514/6c8084e6-edc0-4a7d-a9ea-0cc54defec80)
This is only an example(made in figma) how the website will look, will add many more stylings to the website, so that it will will look attractive to the user.

I'll create the PR ASAP, so that you can review it.🙏🙏

**Comment by sithel** [comment]
Hi there-- really appreciate the enthusiasm and interest for working on the site. That said, we're rather happy with the general look of the site. The narrow UI and boxed sections are the look we like & find useful.  (with the bonus of displaying the same on mobile as on web, which is easier to support with a small dev team) 

We're open to UI/feedback, but perhaps not such a drastic change?

**Comment by Re-n-Im** [comment]
@sithel your app is wonderful, but to understand the logic behind any option, it costs me a lot of tries to see what is happening.
Perhaps the UI for you as a builders of this project is enough eloquent, but for users like me it is not the same. :)
At my work I am building user interfaces and can say - they really matter for the ease of users workflow. And from my practice, there are two main types of users - those who understand more from what they read, and others - that understand better from graphic content. In this line of thought, changes that @yaten2302 suggests are good, but they could be made even better.
