### ISSUE TITLE
Feature: Name generated PDFs based on original PDF

### ISSUE THREAD

**Issue by acestronautical** [momijizukamori/bookbinder-js#93]
Currently we generate files named like "aggregate.pdf" it would be nice if the downloaded files were named based on the original PDF name. So like "china and the mongols.pdf" becomes "china and the mongols - typeset - 4signature -duplex - aggregate.pdf" or something similar.

**Comment by sithel** [comment]
the name for a long while was trying to hold some of the settings info -- now with @cass-kazumori 's work, that is no longer needed. What is the scheme you're proposing exactly? 

We have the ZIP file name
We have the file names within the ZIP file

I agree that the original file name should be repeated through all files. 
Don't have the bandwidth to propose something now but would appreciate seeing a specific schema being proposed before PR work begins (but 👍 to the work)

**Comment by acestronautical** [comment]
I am proposing as shown in: https://github.com/momijizukamori/bookbinder-js/pull/104

Sorry it was easier to just implement than think about.
Let me know if the schema in my PR looks good, am willing to change to whatever folks think is best.
